import Head from 'next/head'
import Navigation from './navigation'
import Footer from './footer'
import styles from '../styles/Home.module.css'


const Container = (props) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Cuqu Lab</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/lgbtqiflag.ico' />
            </Head>
            <Navigation />
            <main className={styles.main}>
                {props.children}
            </main>
            <Footer />
        </div>
    )
}

export default Container